#!/bin/bash
# ----------------------------------------------------------
# CLEAN REINSTALL + HYPRLAND CONFIG RESTORE
# ----------------------------------------------------------

echo "⚠️  This will remove configs and reinstall packages for: cava, cmatrix, waybar, htop, hypr, kitty, fish"
echo "Make sure to backup any custom configs you want to keep!"
read -p "Proceed? (y/N): " confirm
if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
    echo "Aborted."
    exit 1
fi

# 1️⃣ Remove old configs and binaries
echo "🗑 Removing old configs..."
rm -rf ~/.config/cava ~/.config/cmatrix ~/.config/waybar ~/.config/htop ~/.config/hypr ~/.config/kitty ~/.config/fish
rm -f ~/.local/bin/matrix

# 2️⃣ Reinstall packages (via pacman / yay)
echo "💿 Reinstalling packages..."
PKGS="cava cmatrix waybar htop hyprland kitty fish"
for pkg in $PKGS; do
    if pacman -Qi $pkg &> /dev/null; then
        sudo pacman -S --noconfirm --needed $pkg
    else
        # Try yay for AUR packages
        if command -v yay &> /dev/null; then
            yay -S --noconfirm --needed $pkg
        else
            echo "⚠️ $pkg not found in pacman or yay"
        fi
    fi
done

# 3️⃣ Restore original Hyprland config
HYPR_CONFIG="$HOME/.config/hypr/hyprland.conf"
mkdir -p ~/.config/hypr
cat > $HYPR_CONFIG <<'EOF'
# #######################################################################################
# AUTOGENERATED HYPRLAND CONFIG.
# MODIFIED VERSION (WOFI LAUNCHER)
# #######################################################################################

autogenerated = 1

################
### MONITORS ###
################

monitor=,preferred,auto,1.2

###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
$browser = chromium --user-data-dir=$HOME/.config/chromium

#################
### AUTOSTART ###
#################

exec-once = waybar
exec-once = nm-applet

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 5
    gaps_out = 20
    border_size = 2

    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 3
        passes = 1
        vibrancy = 0.1696
    }
}

animations {
    enabled = yes, please :)

    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1
    bezier = quick,0.15,0,0.1,1

    animation = global,1,10,default
    animation = border,1,5.39,easeOutQuint
    animation = windows,1,4.79,easeOutQuint
    animation = fade,1,3.03,quick
    animation = workspaces,1,1.94,almostLinear,fade
}

###################
### LAYOUT ########
###################

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = false
}

#############
### INPUT ###
#############

input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace
gesture = 3, vertical, workspace

###################
### KEYBINDINGS ###
###################

$mainMod = SUPER

# terminal
bind = $mainMod, Q, exec, $terminal

# close window
bind = $mainMod, C, killactive,

# file manager
bind = $mainMod, E, exec, $fileManager

# launcher
bind = $mainMod, M, exec, $menu

# chromium
bind = $mainMod, O, exec, chromium --user-data-dir=$HOME/.config/chromium

# floating
bind = $mainMod, V, togglefloating,

# reload config
bind = $mainMod SHIFT, R, exec, hyprctl reload

# logout
bind = $mainMod SHIFT, M, exec, hyprctl dispatch exit

# layout
bind = $mainMod, P, pseudo,
bind = $mainMod, J, layoutmsg, togglesplit

# focus movement
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# move window workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# scratchpad
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# workspace scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# move windows
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# screenshot
bind = , Print, exec, grim -g "$(slurp)" ~/Pictures/screenshot.png

##############################
### WINDOW RULES #############
##############################

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}
EOF

echo "✅ Clean reinstall and Hyprland config restored."
echo "⚠️ Restart Hyprland or reboot to apply changes."
