# MAIN HYPRLAND CONFIG LOADER

source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/programs.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/env.conf
source = ~/.config/hypr/config/look.conf
source = ~/.config/hypr/config/layout.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/keybinds.conf

# personal overrides
source = ~/.config/hypr/custom/override.conf
