general {
    gaps_in = 4
    gaps_out = 8
    border_size = 0
}

decoration {
    rounding = 15
    blur {
        enabled = true
        size = 5
        passes = 3
        new_optimizations = true
    }
}

# Kitty specific window rule
windowrulev2 = opacity 0.85 0.85,class:(kitty)
windowrulev2 = float, class:(hacker_matrix)
windowrulev2 = size 100% 100%, class:(hacker_matrix)
windowrulev2 = center, class:(hacker_matrix)
windowrulev2 = opacity 0.70 0.70, class:(hacker_matrix)
windowrulev2 = monitor 0, class:(hacker_matrix)
