$mainMod = SUPER

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, M, exec, $menu
bind = $mainMod, O, exec, $browser

bind = $mainMod, V, togglefloating

bind = $mainMod SHIFT, R, exec, hyprctl reload
bind = $mainMod SHIFT, M, exec, hyprctl dispatch exit

bind = $mainMod, P, pseudo
bind = $mainMod, J, layoutmsg, togglesplit

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = , F12, exec, grim ~/Pictures/screenshot-$(date +%s).png
bind = SHIFT, F10, exec, grim -g "$(slurp)" ~/Pictures/screenshot-$(date +%s).png

# show/hide| waybar
bind = SHIFT, backslash, exec, pkill -SIGUSR1 waybar

# Hacker Mode (CMatrix)
bind = $mainMod SHIFT, X, exec, kitty --class hacker_matrix -e cmatrix -u 3 -C cyan -b -a
