dwindle {
    pseudotile = true
    preserve_split = true
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

# Newer Hyprland syntax (latest docs)
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.18, match:namespace waybar
