#!/usr/bin/env node

/**
 * ---------------------------------------------------------
 * PROJECT:  EXOCORE SYSTEM ENGINE (Deep Sync Edition)
 * AUTHOR:   Choru Official (Johnsteve Costanos)
 * VERSION:  1.3.0 (GTK, Qt, Electron & Portal Sync)
 * ---------------------------------------------------------
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Paths
const HOME = process.env.HOME;
const WALL_DIR = path.join(HOME, 'Pictures/Pixel-Google-Image');
const CONFIG_DIR = path.join(HOME, '.config/waybar');
const STYLE_FILE = path.join(CONFIG_DIR, 'style.css');
const STATE_FILE = path.join(CONFIG_DIR, 'current_theme.txt');

try {
    // 1. Theme State Logic
    if (!fs.existsSync(STATE_FILE)) fs.writeFileSync(STATE_FILE, 'dark');
    let current = fs.readFileSync(STATE_FILE, 'utf8').trim();
    let next = current === 'dark' ? 'light' : 'dark';

    // 2. Color Palette Configuration
    const theme = {
        dark: {
            bg: 'linear-gradient(45deg, rgba(20, 20, 20, 0.95), rgba(40, 40, 40, 0.95))',
            fg: '#ffffff',
            accent: '#8ab4f8',
            clock: 'linear-gradient(90deg, #4285F4, #9b51e0)',
            border: 'rgba(255, 255, 255, 0.1)',
            gtk: 'prefer-dark',
            kvantum: 'KvLibadwaitaDark'
        },
        light: {
            bg: 'linear-gradient(45deg, rgba(245, 245, 245, 0.95), rgba(255, 255, 255, 0.95))',
            fg: '#202124',
            accent: '#1a73e8',
            clock: 'linear-gradient(90deg, #ffffff, #e8eaed)',
            border: 'rgba(0, 0, 0, 0.1)',
            gtk: 'prefer-light',
            kvantum: 'KvLibadwaita'
        }
    }[next];

    // 3. CSS Template Generation (Waybar)
    const cssContent = `/** Generated by Exocore (Choru Official) **/
    * {
        border: none; border-radius: 0;
        font-family: "JetBrainsMono Nerd Font", sans-serif;
        font-size: 14px; font-weight: 800;
    }
    window#waybar { background: transparent; }
    #custom-launcher {
    background: linear-gradient(45deg, #1793d1, #1f3d7a);
    color: white; padding: 0 15px; margin: 5px; border-radius: 20px;
    }
    #custom-theme-toggle, #workspaces, #custom-bt, #custom-wifi, #custom-mem, #custom-bat {
    background: ${theme.bg}; color: ${theme.fg};
    padding: 0 15px; margin: 5px 3px; border-radius: 20px;
    border: 1px solid ${theme.border};
    }
    #custom-clock {
    background: ${theme.clock}; color: ${theme.fg};
    padding: 0 20px; margin: 5px 0; border-radius: 0 20px 20px 0;
    }
    #custom-google-center {
    background: #ffffff; color: #4285F4;
    padding: 0 15px; margin: 5px 0; border-radius: 20px 0 0 20px;
    }
    `;

    // 4. File Operations
    fs.writeFileSync(STYLE_FILE, cssContent);
    fs.writeFileSync(STATE_FILE, next);

    // 5. GLOBAL DEEP SYNC (The "Magic" Part)
    console.log(`Deep syncing ${next.toUpperCase()} mode...`);

    // A. GTK 3/4 Sync (Chrome, Discord, VSCode)
    execSync(`gsettings set org.gnome.desktop.interface color-scheme "${theme.gtk}"`);
    execSync(`gsettings set org.gnome.desktop.interface gtk-theme "${next === 'dark' ? 'Adwaita-dark' : 'Adwaita'}"`);

    // B. Qt Sync (Dolphin) - Needs Kvantum installed
    try {
        execSync(`kvantummanager --set ${theme.kvantum} > /dev/null 2>&1`);
    } catch (e) { console.log("Kvantum not found, skipping Dolphin sync."); }

    // C. XDG Portal & Dconf (Force Electron apps like Discord/Spotify to see Dark Mode)
    execSync(`dconf write /org/gnome/desktop/interface/color-scheme "'${theme.gtk}'"`);

    // D. Fish Shell Sync
    execSync(`fish -c "${next === 'dark' ? 'exocore' : 'anime'}" > /dev/null 2>&1`);

    // E. Spotify Sync (If using Spicetify)
    try {
        const spicetifyTheme = next === 'dark' ? 'catppuccin' : 'bloom'; // Palitan base sa trip mo
        // execSync(`spicetify config current_theme ${spicetifyTheme} color_scheme ${next} && spicetify apply`);
    } catch (e) {}

    // 6. Wallpaper Transition (swww)
    const folder = path.join(WALL_DIR, next);
    if (fs.existsSync(folder)) {
        const files = fs.readdirSync(folder).filter(f => /\.(jpg|jpeg|png|gif)$/i.test(f));
        if (files.length > 0) {
            const randomWall = files[Math.floor(Math.random() * files.length)];
            execSync(`swww img "${path.join(folder, randomWall)}" --transition-type grow --transition-pos center --transition-fps 60`);
        }
    }

    // 7. Refresh Waybar
    execSync('pkill -USR2 waybar || (pkill waybar; waybar &)');

} catch (err) {
    console.error("Exocore Script Error:", err.message);
}
