#!/usr/bin/env node

/**
 * ---------------------------------------------------------
 * PROJECT:  EXOCORE SYSTEM ENGINE (Classic Sync)
 * AUTHOR:   Choru Official (Johnsteve Costanos)
 * VERSION:  1.2.0 (Stable & Lightweight)
 * ---------------------------------------------------------
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const HOME = process.env.HOME;
const WALL_DIR = path.join(HOME, 'Pictures/Pixel-Google-Image');
const CONFIG_DIR = path.join(HOME, '.config/waybar');
const STYLE_FILE = path.join(CONFIG_DIR, 'style.css');
const STATE_FILE = path.join(CONFIG_DIR, 'current_theme.txt');

try {

    if (!fs.existsSync(STATE_FILE)) fs.writeFileSync(STATE_FILE, 'dark');
    let current = fs.readFileSync(STATE_FILE, 'utf8').trim();
    let next = current === 'dark' ? 'light' : 'dark';


    const theme = {
        dark: {
            bg: 'linear-gradient(45deg, rgba(20, 20, 20, 0.95), rgba(40, 40, 40, 0.95))',
            fg: '#ffffff',
            accent: '#8ab4f8',
            clock: 'linear-gradient(90deg, #4285F4, #9b51e0)',
            border: 'rgba(255, 255, 255, 0.1)',
            gtk: 'prefer-dark'
        },
        light: {
            bg: 'linear-gradient(45deg, rgba(245, 245, 245, 0.95), rgba(255, 255, 255, 0.95))',
            fg: '#202124',
            accent: '#1a73e8',
            clock: 'linear-gradient(90deg, #ffffff, #e8eaed)',
            border: 'rgba(0, 0, 0, 0.1)',
            gtk: 'prefer-light'
        }
    }[next];


    const cssContent = `/**
    * Generated by Exocore (Choru Official)
    * Theme: ${next.toUpperCase()}
    */

    * {
        border: none;
        border-radius: 0;
        font-family: "JetBrainsMono Nerd Font", "Roboto", sans-serif;
        font-size: 14px;
        font-weight: 800;
    }

    window#waybar { background: transparent; }

    #custom-launcher {
        background: linear-gradient(45deg, #1793d1, #1f3d7a);
        color: white;
        padding: 0 15px;
        margin: 5px;
        border-radius: 20px;
        box-shadow: 0 4px 10px rgba(0,0,0,0.2);
    }

    #custom-theme-toggle, #workspaces, #custom-bt, #custom-wifi, #custom-mem, #custom-bat {
        background: ${theme.bg};
        color: ${theme.fg};
        padding: 0 15px;
        margin: 5px 3px;
        border-radius: 20px;
        border: 1px solid ${theme.border};
    }

    #workspaces button.active {
        color: ${theme.accent};
        background: rgba(138, 180, 248, 0.15);
    }

    #custom-google-center {
        background: #ffffff;
        color: #4285F4;
        font-size: 18px;
        padding: 0 15px;
        margin: 5px 0;
        border-radius: 20px 0 0 20px;
    }

    #custom-clock {
        background: ${theme.clock};
        color: ${theme.fg};
        padding: 0 20px;
        margin: 5px 0;
        border-radius: 0 20px 20px 0;
        border-left: 1px solid ${theme.border};
    }
    `;

    fs.writeFileSync(STYLE_FILE, cssContent);
    fs.writeFileSync(STATE_FILE, next);

    console.log(`Switching system to ${next} mode...`);
    try {

        execSync(`gsettings set org.gnome.desktop.interface color-scheme "${theme.gtk}"`);
        
        execSync(`fish -c "${next === 'dark' ? 'exocore' : 'anime'}" > /dev/null 2>&1 || true`);
    } catch (e) {
        console.error("Theming Sync Error:", e.message);
    }

    const folder = path.join(WALL_DIR, next);
    if (fs.existsSync(folder)) {
        const files = fs.readdirSync(folder).filter(f => /\.(jpg|jpeg|png|gif)$/i.test(f));
        if (files.length > 0) {
            const randomWall = files[Math.floor(Math.random() * files.length)];
            execSync(`swww img "${path.join(folder, randomWall)}" --transition-type grow --transition-pos center --transition-fps 60`);
        }
    }

    execSync('pkill -USR2 waybar || (pkill waybar; waybar &)');

} catch (err) {
    console.error("Exocore Script Error:", err.message);
}
